on: [push]
name: Build Chronos
jobs:
  build:
    runs-on: [ windows-2019 ]
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1
      - name: Setup cache for CEF
        uses: actions/cache@v3
        with:
          path: cef-cache/*/
          key: cef-${{ runner.os }}-${{ hashFiles('setup-cef.bat') }}
      - name: Setup CEF
        run: .\setup-cef.bat
      - name: Compile Chronos
        run: msbuild /m /p:Platform=Win32 /p:Configuration=R64_CSG
      - name: Prepare upload
        run: move R32 Chronos
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: Chronos
          path: Chronos
